image: gitlab-ci

stages:
  - test
  - build
  - integrationTest
  - staging
  - production

lint:
  stage: test
  script:
    - echo "XXX lint me"

unittest:
  stage: test
  script:
    - echo "XXX run tests"

build-docker:
  stage: build
  script:
    - make build-image
  
push-to-registry:
  stage: build
  script:
    - make upload-image