version: "3.11"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "80:80"
    networks:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  redis:
    image: redis
    networks:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  app:
    name: app
