kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  # labels:
  #   type: local
  #   app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/redis-data"
