apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
        volumeMounts:
          - name: redis-data
            mountPath: {{ .Values.redis.volume.mountPath }}
        ports:
          - containerPort: {{ .Values.redis.port }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.redis.port }}
    targetPort: {{ .Values.redis.port }}
  selector:
    app: redis