apiVersion: apps/v1
kind: Deployment
metadata:
  name: komplikovana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komplikovana
  template:
    metadata:
      labels:
        app: komplikovana
    spec:
      containers:
      - image: 532993743491.dkr.ecr.eu-central-1.amazonaws.com/komplikovana
        name: komplikovana
        #imagePullPolicy: Never
        imagePullPolicy: IfNotPresent